### ISSUE TITLE
Downloading Data ?

### ISSUE THREAD

**Issue by keithfraley** [Mictronics/readsb#39]
When I run this application, it appears to be downloading a lot of data, almost 1:1 for what it is pushing out.  I dont have MLAT enabled (as far as I know) can you think of another reason the application would be downloading dozens of MBS per day?

**Comment by Mictronics** [comment]
By default, readsb is not pulling data from somewhere. That's only the case when a netconnector is configured.
Please post the content of /etc/default/readsb.

**Comment by TanerH** [comment]
@keithfraley - how are you invoking readsb (what's your commandline look like)?

And for that matter, what are you using to measure the traffic in/out (and how are you certain  it's readsb doing it)?

**Comment by keithfraley** [comment]
sudo ./readsb --quiet --net --gain 40 --net-beast-reduce-interval 5
--net-connector feed.adsbexchange.com,30005,beast_reduce_out

I know how much because I am using LTE and it gives me very detailed usage
stats.  I know its readsb because when I turn it off the network
traffic stops. all together as it is the only thing running on the pi

**Comment by wiedehopf** [comment]
It's an issue on the side of adsbexchanged.

I'll check that it's looked into.

**Comment by Mictronics** [comment]
What amount of data we are talking about?

In terms of rate, my local installations has avg 2kbytes/s/month incoming and avg 20kbytes/s/month outgoing while feeding adsbexchange with beast and mlat, and skybup with beast.
Total amount of data unknown.

**Comment by wiedehopf** [comment]
Can you stop readsb because i seriously doubt it's the issue.
If it's not readsb then the traffic should continue.

Also check that you're not running mlat-client?
```
pgrep -a mlat
pgrep -a socat
```

**Comment by keithfraley** [comment]
thanks guys! I will take a look

**Comment by Mictronics** [comment]
@keithfraley Please report back readsb related findings or close this PR in case readsb was not the reason.

**Comment by Mictronics** [comment]
No additional information provided. Considered not readsb related.
