### ISSUE TITLE
webapp: Source map missing or inaccessible

### ISSUE THREAD

**Issue by mikenye** [Mictronics/readsb#40]
Hi,

When deploying the webapp, I've noticed that there are 404 errors being logged server side due to two missing files:

`http://readsb/script/leaflet-src.js.map`
`http://readsb/script/bootstrap.bundle.min.js.map`

My process to make the webapp is as follows:

```
cd readsb/webapp
npm install
npm run build
npm install source-map
```

Then serve the `readsb/webapp/src` folder via a simple web server.

I'm unsure if this is causing a problem.

The website renders and appears to operate fine on Firefox (73.0 64-bit).

Running on Safari (Version 13.0.3 (13608.3.10.10.1)) I get a dialog box saying "Undefined" with a link to close the dialog. After hitting close, some information loads but ultimately I'm left with a spinning progress indicator in the top left of the screen.

Thanks.

Kind regards,
Mike Nye

**Comment by Mictronics** [comment]
The missing map files are part of the third-party packages, leaflet and bootstrap in that case. I will not include them, only required for debugging these packages.

Is there any other error message indicated in the developer console when "undefined" popup appears?

**Comment by Mictronics** [comment]
dev branch has it disabled now. However, you can also disable JS source maps in your browser. Chrome has this in settings for developer console. Other browsers I don't know.

**Comment by mikenye** [comment]
Thanks for the info. I don't have a lot of knowledge/experience with npm so thanks for bearing with me.

In the developer console, when the "undefined" dialog appears, I have the following errors logged to the developer console:

- `Viewport argument key "minimal-ui" not recognized and ignored` (http://readsb:8:9)
- `Failed to load resource: the server responded with a status of 404 (Not Found)` (http://readsb/css/bootstrap/bootstrap.min.css.map)
- `Failed to load resource: the server responded with a status of 404 (Not Found)` (http://readsb/script/bootstrap.bundle.min.js.map)
- `Failed to load resource: the server responded with a status of 404 (Not Found)` (http://readsb/script/leaflet-src.js.map)

After pressing "close" on the "undefined" dialog, I get the following additional errors logged to the developer console:

- `Unhandled Promise Rejection: undefined` (anonymous function), rejectPromoise, promiseReactionJob
- `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.db.transaction')` PutSetting - database.ts:160, SiteLat - settings.ts:67, (anonymous function) - readsb.ts:76, promiseReactionJob

In the background I can see the page has rendered without the aircraft, however it is "dimmed out" with a loading icon.

I've taken screenshots: https://imgur.com/a/qspjOxu

Let me know if there's anything else I can do to help.

Thanks.

Kind regards,
Mike Nye

**Comment by Mictronics** [comment]
Thanks for the details. Seems to be the database is not setup or not ready when the page is loading. However, I will have difficulties to setup Safari, so debugging is tricky.

**Comment by mikenye** [comment]
No problems. Is the database not being ready something to do with my server side configuration?

I'm able to access the files under http://readsb/db/ and http://readsb/data/ before opening http://readsb/index.html/

If it helps, happy to arrange a zoom session and do a desktop share if this is useful to you.

**Comment by mikenye** [comment]
Its worth noting that Safari on iOS seems to work fine.

**Comment by Mictronics** [comment]
And what is the difference between Safari in your first PR post and the last one?

**Comment by mikenye** [comment]
Apologies - my original post referred to Safari Version 13.0.3 (13608.3.10.10.1) running on macOS "High Sierra" 10.13.6.
