### ISSUE TITLE
Operation not supported set_lpf_mode

### ISSUE THREAD

**Issue by shodan007** [Mictronics/readsb#48]
Mon May 25 15:27:45 2020 CDT  Mictronics v3.8.3 starting up.
bladeRF: unknown FPGA size, skipping FPGA loadbladerf_set_lpf_mode failed: Operation not supported

bladeRF-cli version:        1.8.0-0.2019.07-4+b1
libbladeRF version:         2.2.1-0.2019.07-4+b1

Firmware version:           2.3.2
FPGA version:               0.11.0 (configured by USB host)

**Comment by Mictronics** [comment]
Did you set the option `--bladerf-fpga=<path> Use alternative FPGA bitstream ('' to disable FPGA load)` correct?
`bladeRF: unknown FPGA size, skipping FPGA load` this error is an indication that the FPGA firmware was not found in default locations `/usr/share/Nuand/bladeRF/` and therefore not loaded.

However, for readsb the bladeRF firmware is located in `/usr/share/readsb/bladerf/decimate8-x40.rbf`.

See https://github.com/Mictronics/readsb/tree/master/bladerf

**Comment by Mictronics** [comment]
@shodan007 Please close the issue in case problem is solved. Otherwise report back if the error persists.

**Comment by shodan007** [comment]
@Mictronics will using Nuand's adsbxA4.rbf not work?  

sudo ./dump1090 --bladerf-fpga /usr/share/Nuand/bladeRF/adsbxA4.rbf 
Sat Jun  6 14:06:40 2020 CDT  dump1090-fa  starting up.
bladeRF: loading FPGA bitstream from /usr/share/Nuand/bladeRF/adsbxA4.rbf
Calibration TIMEOUT (0x16, 0x80)
[ERROR @ host/libraries/libbladeRF/src/board/bladerf2/rfic_host.c:361] _rfic_host_set_sample_rate: ad9361_set_rx_sampling_freq(phy, rate) failed: An unexpected error occurred
[ERROR @ host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c:1087] bladerf2_set_sample_rate: rfic->set_sample_rate(dev, ch, rate) failed: An unexpected error occurred
bladerf_set_sample_rate failed: An unexpected error occurred
[ERROR @ host/libraries/libbladeRF/src/backend/usb/nios_access.c:77] Failed to receive NIOS II response: Operation timed out
[ERROR @ host/libraries/libbladeRF/src/backend/usb/nios_access.c:77] Failed to receive NIOS II response: Operation timed out

**Comment by Mictronics** [comment]
decimate8-x40.rbf that comes with readsb works?

**Comment by shodan007** [comment]
The included file doesn't work

sudo ./readsb --bladerf-fpga ./bladerf/decimate8-x40.rbf 
Mon Jun  8 01:48:04 2020 CDT  Mictronics v3.8.3 starting up.
bladeRF: loading FPGA bitstream from ./bladerf/decimate8-x40.rbf
[WARNING @ host/libraries/libbladeRF/src/board/bladerf2/common.c:183] Detected potentially incorrect FPGA file (length was 1191788, expected 2632660).
[ERROR @ host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c:2178] bladerf2_load_fpga: fpga file invalid: incorrect file size
bladerf_load_fpga() failed: Invalid operation or parameter

**Comment by Mictronics** [comment]
That means adsbxA4.rbf is at least a valid FPGA firmware that loads but has runtime issues.
The file that comes with reads is one taken over from dump1090-fa, don't know how old or who created this.

Anyway, I do not own a bladeRF so no chance for testing or troubleshooting. Not sure how to help or solve that issue.
